# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PocketGram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PocketGram
  pod 'Alamofire'
  pod "AlamofireImage"


  target 'PocketGramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PocketGramUITests' do
    # Pods for testing
  end

end
